package housfy

import com.google.gson.annotations.SerializedName

data class Property(

	@SerializedName("uuid") val uuid: String,
	@SerializedName("providerCode") val providerCode: String,
	@SerializedName("providerPropertyId") val providerPropertyId: Int,
	@SerializedName("providerPropertyUrl") val providerPropertyUrl: String,
	@SerializedName("providerPropertyTitle") val providerPropertyTitle: String,
	@SerializedName("publishedDate") val publishedDate: String,
	@SerializedName("relevance") val relevance: Int,
	@SerializedName("typeId") val typeId: Int,
	@SerializedName("typeCode") val typeCode: String,
	@SerializedName("reservedDate") val reservedDate: String,
	@SerializedName("soldDate") val soldDate: String,
	@SerializedName("locationId") val locationId: Int,
	@SerializedName("sizes") val sizes: Sizes,
	@SerializedName("size") val size: Int,
	@SerializedName("photos") val photos: List<String>,
	@SerializedName("numberOfBedrooms") val numberOfBedrooms: Int,
	@SerializedName("numberOfBathrooms") val numberOfBathrooms: Int,
	@SerializedName("userName") val userName: String,
	@SerializedName("userPhone") val userPhone: UserPhone,
	@SerializedName("operationTypeCode") val operationTypeCode: String,
	@SerializedName("isVisible") val isVisible: Boolean,
	@SerializedName("description") val description: String,
	@SerializedName("tags") val tags: List<Int>,
	@SerializedName("canScheduleVisits") val canScheduleVisits: Boolean,
	@SerializedName("stateLocationName") val stateLocationName: String,
	@SerializedName("cityLocationName") val cityLocationName: String,
	@SerializedName("districtLocationName") val districtLocationName: String,
	@SerializedName("neighborhoodLocationName") val neighborhoodLocationName: String,
	@SerializedName("streetName") val streetName: String,
	@SerializedName("streetNumber") val streetNumber: String,
	@SerializedName("floor") val floor: String,
	@SerializedName("door") val door: String,
	@SerializedName("floorDoorLabel") val floorDoorLabel: String,
	@SerializedName("latitude") val latitude: Double,
	@SerializedName("longitude") val longitude: Double,
	@SerializedName("showApproximateAddress") val showApproximateAddress: String,
	@SerializedName("postalCode") val postalCode: String,
	@SerializedName("price") val price: Price,
	@SerializedName("priceSize") val priceSize: PriceSize,
	@SerializedName("priceChangePercentage") val priceChangePercentage: String,
	@SerializedName("isNew") val isNew: Boolean,
	@SerializedName("isPriceUpdated") val isPriceUpdated: Boolean,
	@SerializedName("isReserved") val isReserved: Boolean,
	@SerializedName("isSold") val isSold: Boolean,
)